import type { Asset, AssetDetail, User, Activity } from "@/types";

export const mockAssets: Asset[] = [
  {
    id: "AG-8829-X",
    name: "MacBook Pro 16\"",
    type: "LAPTOP",
    manufacturer: "Apple Inc.",
    model: "MacBook Pro 16-inch (M3)",
    serialNumber: "C02FX1G9MD6R",
    status: "COMPLIANT",
    assignedTo: "Alex Sterling",
    department: "Engineering Department",
    location: "HQ - San Francisco",
    category: "Laptops",
  },
  {
    id: "AG-1142-S",
    name: "Dell PowerEdge R750",
    type: "SERVER",
    manufacturer: "Dell Technologies",
    model: "PowerEdge R750",
    serialNumber: "SV-821-XJ3-L",
    status: "CRITICAL",
    assignedTo: "Infrastructure Team",
    department: "NY-DataCenter-B12",
    location: "Data Center East",
    category: "Servers",
  },
  {
    id: "AG-4491-N",
    name: "Cisco Catalyst 9300",
    type: "NETWORK",
    manufacturer: "Cisco Systems",
    model: "Catalyst 9300",
    serialNumber: "FXS21345L0K",
    status: "COMPLIANT",
    assignedTo: "Core Infrastructure",
    department: "IT Operations",
    location: "HQ - Network Room",
    category: "Network",
  },
  {
    id: "AG-9902-W",
    name: "Workstation Z8 Fury",
    type: "WORKSTATION",
    manufacturer: "HP Enterprise",
    model: "Z8 Fury G5",
    serialNumber: "HP-Z8-98921-A",
    status: "PENDING",
    assignedTo: "Visual Design Team",
    department: "Design",
    location: "HQ - Studio Floor",
    category: "Workstations",
  },
  {
    id: "AG-2023-8842",
    name: "MacBook Pro 16\"",
    type: "LAPTOP",
    manufacturer: "Apple Inc.",
    model: "MacBook Pro 16-inch (M2)",
    serialNumber: "C02FX9KMD3R",
    status: "COMPLIANT",
    assignedTo: "Alex",
    department: "Engineering",
    location: "HQ - San Francisco",
    category: "Laptops",
  },
  {
    id: "AG-2023-1109",
    name: "Dell UltraSharp 27",
    type: "MONITOR",
    manufacturer: "Dell",
    model: "UltraSharp U2723DE",
    serialNumber: "DL-US27-44512",
    status: "COMPLIANT",
    assignedTo: "Alex",
    department: "Engineering",
    location: "HQ - San Francisco",
    category: "Monitors",
  },
];

export const mockAssetDetail: AssetDetail = {
  id: "AG-8829-PRO",
  name: "MacBook Pro 16\" - Engineering",
  type: "LAPTOP",
  manufacturer: "Apple Inc.",
  model: "MacBook Pro 16-inch (M2 Max)",
  serialNumber: "C02FX1G9MD6R",
  status: "COMPLIANT",
  assignedTo: "Alex Sterling",
  department: "Infrastructure & Engineering",
  location: "HQ - San Francisco (Room 402)",
  category: "High-End Workstation",
  cpu: "12-Core CPU / 38-Core GPU",
  ram: "64GB LPDDR5X",
  storage: "2TB SSD NVMe",
  os: "macOS Sonoma 14.2.1",
  macAddress: "3C:06:30:4F:A1:99",
  ipAddress: "192.168.1.144",
  deviceConfig: "Config: PRO-STATION-2024-V2\nPeripherals: Magic Mouse, CalDigit TS4 Dock\nAccessories: 140W Power Adapter, Braided Magsafe Cable",
  encryptionStatus: "FileVault Active",
  antivirus: "CrowdStrike 6.1",
  compliance: "SOC2 / HIPAA",
  lastAudit: "Oct 14, 2023",
  owner: "Product Ops Dept.",
  costCenter: "CC-8812-ENG",
  roomNumber: "Room 402",
};

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Julianne Davenport",
    email: "j.davenport@assetsecure.io",
    role: "ADMIN",
    department: "Information Technology",
    lastLogin: "2 hours ago",
    status: "active",
  },
  {
    id: "u2",
    name: "Marcus Kane",
    email: "m.kane@assetsecure.io",
    role: "USER",
    department: "Compliance & Risk",
    lastLogin: "Yesterday, 4:15 PM",
    status: "active",
  },
  {
    id: "u3",
    name: "Sarah Rosencrantz",
    email: "s.rose@assetsecure.io",
    role: "USER",
    department: "External Audit",
    lastLogin: "Oct 24, 2023",
    status: "active",
  },
  {
    id: "u4",
    name: "Tobias Henderson",
    email: "t.henderson@assetsecure.io",
    role: "USER",
    department: "Logistics",
    lastLogin: "Active Now",
    status: "active",
  },
];

export const mockActivity: Activity[] = [
  {
    id: "a1",
    type: "add",
    title: "50 New Laptops Added",
    description: "Provisioned for HR department onboarding.",
    timestamp: "2 hours ago",
  },
  {
    id: "a2",
    type: "warning",
    title: "Compliance Scan Complete",
    description: "3 issues detected in EMEA Data Center.",
    timestamp: "5 hours ago",
  },
  {
    id: "a3",
    type: "alert",
    title: "Decommission Alert",
    description: "Server Rack-42 reached end-of-life status.",
    timestamp: "Yesterday",
  },
  {
    id: "a4",
    type: "info",
    title: "New Admin Assigned",
    description: "Sarah Jenkins granted Auditor permissions.",
    timestamp: "Oct 20, 2023",
  },
];

export const mockDashboardStats = {
  totalAssets: 12482,
  assetGrowth: "+2.4% this month",
  compliance: 98.2,
  complianceStatus: "Target achieved",
  upcomingAudit: {
    title: "Infrastructure Review",
    date: "Scheduled for Oct 24, 2023",
    location: "Data Center East",
  },
  assetsByCategory: [
    { name: "Laptops", count: 5420, growth: "+12%" },
    { name: "Servers", count: 2100, growth: "+5%" },
    { name: "Monitors", count: 3890, growth: "-2%" },
  ],
};
